development:
  adapter: postgresql
  encoding: utf8
  database: anaerp_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: anaerp_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: anaerp_production
  pool: 5
  username: postgres
  password: